### PR TITLE
Update CMapReaderFactory.js

### PR DESCRIPTION
**Pull request by h366163721**
//加载完语言文件后清除缓存,问题:多次打开pdf时不显示文字.

### CODE REVIEW

**Comment by FranckFreiburger** [comment]
- please use English
- please give more details about your changes

**Comment by h366163721** [comment]
Problem: the second loading of the language file is null after one loading. 
As a result, the text will not be displayed when opening PDF for many times
fix: clear the cache after loading the language file.

**Comment by FranckFreiburger** [comment]
need to find a better way to fix this issue. Tweaking `require.cache` is not an option

**Comment by h366163721** [comment]
Is there a better way to deal with it. Please let me know

> 
> 
> need to find a better way to fix this issue. Tweaking `require.cache` is not an option

**Pull request closed without merging**
