### PR TITLE
Implement internal links

### PR DESCRIPTION
**Pull request by markhalonen**
I referenced the react-pdf [commit](https://github.com/wojtekmaj/react-pdf/commit/c8ebed38cd8478b496f84926279ba12d18fd771b) that uses the pdf.js Api to make this work correctly.

### CODE REVIEW

**Comment by FranckFreiburger** [comment]
Hi, I wondering if it is really necessary to add `src/LinkService.js` instead of directly using `import { PDFLinkService } from 'pdfjs-dist/lib/web/pdf_link_service';` in pdfjsWrapper ?

**Comment by markhalonen** [comment]
No, it's probably not necessary. I'll go ahead and remove `src/LinkService.js`

**Comment by markhalonen** [comment]
Done

**Comment by FranckFreiburger** [comment]
thanks !

**Pull request merged**
