### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by philefstat**
adds an example for printing multiple pages

### CODE REVIEW

**Comment by FranckFreiburger** [comment]
please remove my previous example, it is not working any more.

**Comment by philefstat** [comment]
@FranckFreiburger weird, it seems to be working for me without params now... 😂

**Comment by philefstat** [comment]
but i can remove the other example if you want

**Comment by FranckFreiburger** [comment]
ok I remember:
https://github.com/FranckFreiburger/vue-pdf/blob/master/src/pdf.vue#L254
`pageList` is a filter, without this filter, everything is printed.
I should also add a default value for dpi and explain everything in the doc... later, it's experimental !

**Comment by philefstat** [comment]
interesting...

**Pull request merged**
